"use client";

import { motion } from "motion/react";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ChevronLeftIcon, CopyIcon, SparklesIcon, Loader2, LightbulbIcon, FileTextIcon, BotIcon, SettingsIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import API from "@/lib/api";
import { AiLoader } from "@/components/ui/ai-loader";

export default function ImportQuestionnairePage() {
  const router = useRouter();
  const [jsonInput, setJsonInput] = useState("");
  const [isImporting, setIsImporting] = useState(false);
  const [rawPrompt, setRawPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const [promptTemplate, setPromptTemplate] = useState("");
  const [suggestionTemplates, setSuggestionTemplates] = useState(null);
  const [isLoadingPrompt, setIsLoadingPrompt] = useState(true);
  
  const [aiUsage, setAiUsage] = useState({ used: 0, limit: 3, remaining: 3, loaded: false });

  const fetchAiUsage = async () => {
    try {
      const res = await API.get("/questionnaires/ai-usage");
      if (res.data) {
        setAiUsage({ ...res.data, loaded: true });
      }
    } catch (error) {
      console.error("Failed to fetch AI usage:", error);
    }
  };

  useEffect(() => {
    fetchPromptAndTemplates();
    fetchAiUsage();
  }, []);

  const fetchPromptAndTemplates = async () => {
    try {
      const [promptRes, templatesRes] = await Promise.all([
        API.get("/questionnaires/prompt"),
        API.get("/questionnaires/templates")
      ]);
      setPromptTemplate(promptRes.data.prompt);
      setSuggestionTemplates(templatesRes.data.templates);
    } catch (error) {
      toast.error("Failed to load resources from server.");
    } finally {
      setIsLoadingPrompt(false);
    }
  };

  const copyPrompt = () => {
    if (!promptTemplate) return;
    navigator.clipboard.writeText(promptTemplate);
    toast.success("Prompt copied to clipboard!");
  };

  const handleImport = async () => {
    if (!jsonInput.trim()) {
      toast.error("Please paste the JSON generated by the AI.");
      return;
    }

    let parsed;
    try {
      parsed = JSON.parse(jsonInput.trim());
    } catch (e) {
      toast.error("Invalid JSON format. Please ensure you copied valid JSON.");
      return;
    }

    if (!parsed.title || !Array.isArray(parsed.fields)) {
      toast.error("JSON is missing required 'title' or 'fields' array.");
      return;
    }

    setIsImporting(true);
    try {
      const res = await API.post("/questionnaires/import-ai", { json: parsed });
      sessionStorage.setItem("ai_generated_questionnaire", JSON.stringify(res.data));
      toast.success("Validation successful! Opening builder...");
      router.push(`/dashboard/questionnaires/new`);
    } catch (error) {
      toast.error(error.response?.data?.error || error.response?.data?.message || "Failed to validate questionnaire.");
    } finally {
      setIsImporting(false);
    }
  };

  const handleGenerateWithAi = async () => {
    if (!rawPrompt.trim()) {
      toast.error("Please describe what information you need to gather.");
      return;
    }

    setIsGenerating(true);
    try {
      // 1. Generate JSON via Built-in AI (This endpoint validates and returns the JSON without saving)
      const generateRes = await API.post("/questionnaires/generate", { prompt: rawPrompt });

      // 2. Pass data to the Builder UI for review
      sessionStorage.setItem("ai_generated_questionnaire", JSON.stringify(generateRes.data));
      toast.success("Questionnaire generated! Opening builder...");
      router.push(`/dashboard/questionnaires/new`);
    } catch (error) {
      console.error("AI Generation error:", error);
      
      // Handle rate limits and validation errors
      if (error?.response?.status === 429) {
        toast.error("Daily AI generation limit reached. Please use 'Use Your Own AI' or try again tomorrow.");
        fetchAiUsage(); // Refresh limit
      } else if (error?.response?.status === 413 || error?.response?.data?.message?.includes("too long")) {
        toast.error("Prompt is too long. Please shorten your request.");
      } else {
        toast.error(error?.response?.data?.message || "Failed to generate questionnaire with AI.");
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const setTemplate = (type) => {
    if (!suggestionTemplates) {
      toast.error("Templates are still loading, please wait.");
      return;
    }

    if (type === "onboarding" && suggestionTemplates.onboarding) {
      setJsonInput(JSON.stringify(suggestionTemplates.onboarding, null, 2));
      toast.success("Client Onboarding template loaded!");
    } else if (type === "payment" && suggestionTemplates.payment) {
      setJsonInput(JSON.stringify(suggestionTemplates.payment, null, 2));
      toast.success("Payment Terms template loaded!");
    }
  };

  return (
    <div className="p-8 h-full w-full flex flex-col gap-8 relative overflow-x-hidden">
      {/* Background Glow */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/20 blur-[120px] rounded-full pointer-events-none -z-10" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[30%] h-[30%] bg-blue-500/10 blur-[100px] rounded-full pointer-events-none -z-10" />

      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-4 mb-2"
      >
        <Button variant="outline" size="icon" onClick={() => router.push("/dashboard/questionnaires")} className="rounded-full shadow-sm hover:shadow-md transition-all">
          <ChevronLeftIcon className="size-4" />
        </Button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">Import with AI</h1>
          <p className="text-muted-foreground mt-1 text-sm sm:text-base">Generate a complete questionnaire from raw data using ChatGPT or Claude.</p>
        </div>
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <Card className="border-primary/20 bg-gradient-to-r from-primary/10 to-primary/5 backdrop-blur-md shadow-lg relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
            <SparklesIcon className="size-24 text-primary" />
          </div>
          <CardContent className="p-5 flex flex-col gap-4 relative z-10">
            <div className="flex flex-col sm:flex-row sm:items-center gap-2">
              <div className="flex items-center gap-2 text-primary font-semibold">
                <LightbulbIcon className="size-5 animate-pulse" />
                <span>Smart Suggestions:</span>
              </div>
              <p className="text-sm text-foreground/80">Don't have your own data? Start instantly with a ready-made template.</p>
            </div>
            <div className="flex flex-wrap gap-3 w-full">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setTemplate('onboarding')}
                className="gap-2 bg-background/60 hover:bg-background shadow-sm hover:shadow-md transition-all border-primary/10 hover:border-blue-500/30 rounded-full"
              >
                <FileTextIcon className="size-4 text-blue-500" />
                Client Onboarding
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setTemplate('payment')}
                className="gap-2 bg-background/60 hover:bg-background shadow-sm hover:shadow-md transition-all border-primary/10 hover:border-green-500/30 rounded-full"
              >
                <FileTextIcon className="size-4 text-green-500" />
                Payment Terms
              </Button>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <Tabs defaultValue="built-in" className="w-full">
        <TabsList className="grid w-full max-w-md mx-auto grid-cols-2 mb-8 bg-muted/50 p-1 rounded-xl shadow-sm">
          <TabsTrigger value="built-in" className="rounded-lg gap-2 data-[state=active]:bg-background data-[state=active]:shadow-sm">
            <BotIcon className="size-4" /> Built-in AI
          </TabsTrigger>
          <TabsTrigger value="external" className="rounded-lg gap-2 data-[state=active]:bg-background data-[state=active]:shadow-sm">
            <SettingsIcon className="size-4" /> Use Your Own AI
          </TabsTrigger>
        </TabsList>

        <TabsContent value="built-in" className="mt-0 outline-none w-full">
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col h-full w-full">
            <Card className="flex flex-col h-full border-border/50 shadow-lg bg-background/80 backdrop-blur-sm transition-all duration-300 hover:shadow-xl">
              <CardHeader className="pb-4 border-b border-border/50 bg-muted/20">
                <CardTitle className="flex items-center gap-2">
                  <BotIcon className="size-5 text-primary" /> Describe Your Form
                </CardTitle>
                <CardDescription className="text-sm">
                  Explain what kind of questionnaire you need. Our Built-in AI will automatically build the fields, choices, and logic.
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-1 p-6 flex flex-col justify-center min-h-[348px]">
                {isGenerating ? (
                  <AiLoader text="Generating Magic..." />
                ) : (
                  <Textarea 
                    placeholder="e.g. I need a client onboarding form for my web design agency. I want to know their budget, timeline, and link to their current website..."
                    value={rawPrompt}
                    onChange={(e) => setRawPrompt(e.target.value)}
                    disabled={aiUsage.loaded && aiUsage.remaining === 0}
                    className="h-[300px] w-full resize-none text-sm p-4 bg-muted/10 border-border/50 focus-visible:ring-primary/30 transition-colors focus:bg-background leading-relaxed shadow-inner disabled:opacity-50"
                  />
                )}
              </CardContent>
              {!isGenerating && (
                <CardFooter className="pt-2 pb-6 px-6 flex flex-col items-end gap-2">
                  <Button 
                    onClick={handleGenerateWithAi} 
                    disabled={isGenerating || !rawPrompt.trim() || (aiUsage.loaded && aiUsage.remaining === 0)} 
                    className="gap-2 bg-gradient-to-r from-primary to-primary/80 hover:from-primary hover:to-primary shadow-md transition-all hover:scale-[1.05]"
                    size="lg"
                  >
                    <SparklesIcon className="size-5" /> 
                    {aiUsage.loaded && aiUsage.remaining === 0 ? "Limit Reached" : "Generate & Import Form"}
                  </Button>
                  
                  {aiUsage.loaded && (
                    <div className="text-xs text-muted-foreground mr-1">
                      {aiUsage.remaining === 0 ? (
                        <span className="text-destructive font-medium">Daily AI generation limit reached. Please use 'Use Your Own AI'.</span>
                      ) : (
                        <span><span className="font-medium text-foreground">{aiUsage.remaining} of {aiUsage.limit}</span> remaining today</span>
                      )}
                    </div>
                  )}
                </CardFooter>
              )}
            </Card>
          </motion.div>
        </TabsContent>

        <TabsContent value="external" className="mt-0 outline-none w-full">
          <div className="flex flex-col gap-6 w-full">
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
              <Card className="border-border/50 shadow-sm bg-background/80 backdrop-blur-sm">
                <CardHeader className="pb-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="flex items-center gap-3">
                        <span className="flex items-center justify-center size-8 rounded-full bg-gradient-to-br from-primary to-primary/60 text-primary-foreground shadow-sm text-sm font-bold">1</span>
                        Get the System Prompt
                      </CardTitle>
                      <CardDescription className="mt-2 text-sm max-w-[500px]">
                        Copy our highly-optimized system prompt to your clipboard. Paste it into ChatGPT, Claude, or any LLM, followed by the raw data you want to convert into a form.
                      </CardDescription>
                    </div>
                    <Button
                      onClick={copyPrompt}
                      disabled={isLoadingPrompt}
                      className="gap-2 shadow-sm transition-all hover:scale-[1.02]"
                    >
                      {isLoadingPrompt ? <Loader2 className="size-4 animate-spin" /> : <CopyIcon className="size-4" />}
                      Copy Prompt
                    </Button>
                  </div>
                </CardHeader>
              </Card>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
              <Card className="flex flex-col border-border/50 shadow-md bg-background/80 backdrop-blur-sm">
                <CardHeader className="pb-4 border-b border-border/50 bg-muted/10">
                  <CardTitle className="flex items-center gap-3">
                    <span className="flex items-center justify-center size-8 rounded-full bg-gradient-to-br from-primary to-primary/60 text-primary-foreground shadow-sm text-sm font-bold">2</span>
                    Paste Generated JSON
                  </CardTitle>
                  <CardDescription className="text-sm">
                    Once the AI replies with the JSON structure, paste it exactly as-is into the field below.
                  </CardDescription>
                </CardHeader>
                <CardContent className="p-6 flex flex-col justify-center min-h-[268px]">
                  {isImporting ? (
                    <AiLoader text="Validating JSON..." />
                  ) : (
                    <Textarea 
                      placeholder='{\n  "title": "Example Form",\n  "fields": [...]\n}'
                      value={jsonInput}
                      onChange={(e) => setJsonInput(e.target.value)}
                      className="h-[220px] w-full resize-none font-mono text-xs bg-muted/10 border-border/50 focus-visible:ring-primary/30 p-4 text-foreground/80 leading-relaxed transition-colors focus:bg-background shadow-inner"
                    />
                  )}
                </CardContent>
                {!isImporting && (
                  <CardFooter className="pt-2 pb-6 px-6 flex justify-end">
                    <Button 
                      onClick={handleImport} 
                      disabled={isImporting || !jsonInput.trim()} 
                      size="lg"
                      className="gap-2 bg-gradient-to-r from-primary to-primary/80 hover:from-primary hover:to-primary shadow-md transition-all hover:scale-[1.05]"
                    >
                      <SparklesIcon className="size-5" /> 
                      Validate & Open Builder
                    </Button>
                  </CardFooter>
                )}
              </Card>
            </motion.div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
