"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ChevronLeftIcon, CopyIcon, SparklesIcon, Loader2, LightbulbIcon, FileTextIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import API from "@/lib/api";

export default function ImportQuestionnairePage() {
  const router = useRouter();
  const [jsonInput, setJsonInput] = useState("");
  const [isImporting, setIsImporting] = useState(false);
  
  const [promptTemplate, setPromptTemplate] = useState("");
  const [suggestionTemplates, setSuggestionTemplates] = useState(null);
  const [isLoadingPrompt, setIsLoadingPrompt] = useState(true);

  useEffect(() => {
    fetchPromptAndTemplates();
  }, []);

  const fetchPromptAndTemplates = async () => {
    try {
      const [promptRes, templatesRes] = await Promise.all([
        API.get("/questionnaires/prompt"),
        API.get("/questionnaires/templates")
      ]);
      setPromptTemplate(promptRes.data.prompt);
      setSuggestionTemplates(templatesRes.data.templates);
    } catch (error) {
      toast.error("Failed to load resources from server.");
    } finally {
      setIsLoadingPrompt(false);
    }
  };

  const copyPrompt = () => {
    if (!promptTemplate) return;
    navigator.clipboard.writeText(promptTemplate);
    toast.success("Prompt copied to clipboard!");
  };

  const handleImport = async () => {
    if (!jsonInput.trim()) {
      toast.error("Please paste the JSON generated by the AI.");
      return;
    }

    let parsed;
    try {
      parsed = JSON.parse(jsonInput.trim());
    } catch (e) {
      toast.error("Invalid JSON format. Please ensure you copied valid JSON.");
      return;
    }

    if (!parsed.title || !Array.isArray(parsed.fields)) {
      toast.error("JSON is missing required 'title' or 'fields' array.");
      return;
    }

    setIsImporting(true);
    try {
      const res = await API.post("/questionnaires", parsed);
      toast.success("Questionnaire successfully generated!");
      router.push(`/dashboard/questionnaires/${res.data.questionnaire.id}`);
    } catch (error) {
      toast.error(error.response?.data?.error || "Failed to import questionnaire.");
    } finally {
      setIsImporting(false);
    }
  };

  const setTemplate = (type) => {
    if (!suggestionTemplates) {
      toast.error("Templates are still loading, please wait.");
      return;
    }
    
    if (type === "onboarding" && suggestionTemplates.onboarding) {
      setJsonInput(JSON.stringify(suggestionTemplates.onboarding, null, 2));
      toast.success("Client Onboarding template loaded!");
    } else if (type === "payment" && suggestionTemplates.payment) {
      setJsonInput(JSON.stringify(suggestionTemplates.payment, null, 2));
      toast.success("Payment Terms template loaded!");
    }
  };

  return (
    <div className="p-8 h-full max-w-5xl mx-auto flex flex-col gap-8">
      <div className="flex items-center gap-4 mb-2">
        <Button variant="outline" size="icon" onClick={() => router.push("/dashboard/questionnaires")}>
          <ChevronLeftIcon className="size-4" />
        </Button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Import with AI</h1>
          <p className="text-muted-foreground mt-1">Generate a complete questionnaire from raw data using ChatGPT or Claude.</p>
        </div>
      </div>

      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="p-4 flex flex-col gap-3">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2">
            <div className="flex items-center gap-2 text-primary font-medium">
              <LightbulbIcon className="size-5" />
              <span>Smart Suggestions:</span>
            </div>
            <p className="text-sm text-muted-foreground">Don't have your own data? Start instantly with a ready-made template.</p>
          </div>
          <div className="flex gap-3 w-full">
            <Button variant="outline" size="sm" onClick={() => setTemplate('onboarding')} className="flex-1 sm:flex-none gap-2 bg-background shadow-sm">
              <FileTextIcon className="size-4 text-blue-500" />
              Client Onboarding
            </Button>
            <Button variant="outline" size="sm" onClick={() => setTemplate('payment')} className="flex-1 sm:flex-none gap-2 bg-background shadow-sm">
              <FileTextIcon className="size-4 text-green-500" />
              Payment Terms
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Step 1: Prompt */}
        <Card className="flex flex-col border-primary/20 shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-sm font-bold">1</span>
              Copy the Prompt
            </CardTitle>
            <CardDescription>
              Copy this system prompt and paste it into ChatGPT, Claude, or any AI tool, along with your raw text/excel data.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1">
            <div className="relative h-full min-h-[300px]">
              {isLoadingPrompt ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-muted/30 rounded-md">
                   <Loader2 className="size-6 text-primary animate-spin mb-2" />
                   <p className="text-sm font-medium text-muted-foreground">We are cooking, just a moment...</p>
                </div>
              ) : (
                <Textarea 
                  readOnly 
                  value={promptTemplate} 
                  className="h-full resize-none font-mono text-xs bg-muted/30"
                />
              )}
            </div>
          </CardContent>
          <CardFooter className="pt-4 border-t">
            <Button onClick={copyPrompt} className="w-full gap-2">
              <CopyIcon className="size-4" /> Copy Prompt to Clipboard
            </Button>
          </CardFooter>
        </Card>

        {/* Step 2: Paste JSON */}
        <Card className="flex flex-col border-primary/20 shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-sm font-bold">2</span>
              Paste Generated JSON
            </CardTitle>
            <CardDescription>
              Paste the raw JSON output provided by the AI into the field below to automatically create your form.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1">
            <Textarea 
              placeholder='{\n  "title": "Example Form",\n  "fields": [...]\n}'
              value={jsonInput}
              onChange={(e) => setJsonInput(e.target.value)}
              className="h-full min-h-[300px] resize-none font-mono text-xs"
            />
          </CardContent>
          <CardFooter className="pt-4 border-t">
            <Button 
              onClick={handleImport} 
              disabled={isImporting || !jsonInput.trim()} 
              className="w-full gap-2"
            >
              <SparklesIcon className="size-4" /> 
              {isImporting ? "Generating Form..." : "Import Questionnaire"}
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
